/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.views;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import bank.controllers.AccountController;
import bank.controllers.TransactionController;
import bank.controllers.UserController;
import bank.controllers.utils.Response;
import bank.models.Account;
import bank.models.Transaction;
import bank.models.User;

/**
 *
 * @author edangulo
 */
@SuppressWarnings("rawtypes")
public class BankFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form BankFrame
     */
    public BankFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JTabbedPane();
        pnlRegisterUser = new javax.swing.JPanel();
        lblRegisterUser = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnRegisterUser = new javax.swing.JButton();
        pnlCreateAccount = new javax.swing.JPanel();
        lblCreateAccount = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblInitialBalance = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtInitialBalance = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();
        pnlMakeTransaction = new javax.swing.JPanel();
        lblMakeTransaction = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblSourceAccount = new javax.swing.JLabel();
        lblDestinationAccount = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtSourceAccount = new javax.swing.JTextField();
        txtDestinationAccount = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        cmbTransactionType = new javax.swing.JComboBox<>();
        btnMakeTransaction = new javax.swing.JButton();
        pnlUserList = new javax.swing.JPanel();
        lblListUsers = new javax.swing.JLabel();
        scrlUserList = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnRefreshUserList = new javax.swing.JButton();
        pnlAccountList = new javax.swing.JPanel();
        lblListAccounts = new javax.swing.JLabel();
        scrlAccountList = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        btnRefreshAccountList = new javax.swing.JButton();
        pnlTransactionList = new javax.swing.JPanel();
        lblListTransactions = new javax.swing.JLabel();
        scrlTransactionList = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        btnRefreshTransactionList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegisterUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegisterUser.setText("Register User");

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID.setText("ID");

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirstName.setText("Firstname");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastName.setText("Lastname");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age");

        btnRegisterUser.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegisterUser.setText("Register");
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterUserLayout = new javax.swing.GroupLayout(pnlRegisterUser);
        pnlRegisterUser.setLayout(pnlRegisterUserLayout);
        pnlRegisterUserLayout.setHorizontalGroup(
            pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lblRegisterUser)
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(btnRegisterUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterUserLayout.setVerticalGroup(
            pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblRegisterUser)
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterUser)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pnlMain.addTab("Register User", pnlRegisterUser);

        lblCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateAccount.setText("Create Account");

        lblUserID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserID.setText("User ID");

        lblInitialBalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInitialBalance.setText("Initial Balance");

        btnCreateAccount.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCreateAccount.setText("Create");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateAccountLayout = new javax.swing.GroupLayout(pnlCreateAccount);
        pnlCreateAccount.setLayout(pnlCreateAccountLayout);
        pnlCreateAccountLayout.setHorizontalGroup(
            pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateAccountLayout.createSequentialGroup()
                .addGroup(pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateAccountLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblCreateAccount))
                    .addGroup(pnlCreateAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserID)
                            .addComponent(lblInitialBalance))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInitialBalance)
                            .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlCreateAccountLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(btnCreateAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCreateAccountLayout.setVerticalGroup(
            pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateAccountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCreateAccount)
                .addGap(18, 18, 18)
                .addGroup(pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserID))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInitialBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInitialBalance))
                .addGap(18, 18, 18)
                .addComponent(btnCreateAccount)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pnlMain.addTab("Create Account", pnlCreateAccount);

        lblMakeTransaction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMakeTransaction.setText("Make Transaction");

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblType.setText("Type");

        lblSourceAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSourceAccount.setText("Source Account");

        lblDestinationAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDestinationAccount.setText("Destination Account");

        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmount.setText("Amount");

        txtDestinationAccount.setToolTipText("");

        cmbTransactionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw", "Transfer" }));

        btnMakeTransaction.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnMakeTransaction.setText("Execute");
        btnMakeTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMakeTransactionLayout = new javax.swing.GroupLayout(pnlMakeTransaction);
        pnlMakeTransaction.setLayout(pnlMakeTransactionLayout);
        pnlMakeTransactionLayout.setHorizontalGroup(
            pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeTransactionLayout.createSequentialGroup()
                .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeTransactionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType)
                            .addComponent(lblAmount)
                            .addComponent(lblDestinationAccount)
                            .addComponent(lblSourceAccount))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDestinationAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSourceAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTransactionType, 0, 485, Short.MAX_VALUE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlMakeTransactionLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lblMakeTransaction)))
                .addContainerGap())
            .addGroup(pnlMakeTransactionLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(btnMakeTransaction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMakeTransactionLayout.setVerticalGroup(
            pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeTransactionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblMakeTransaction)
                .addGap(18, 18, 18)
                .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addGap(18, 18, 18)
                .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSourceAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSourceAccount))
                .addGap(18, 18, 18)
                .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestinationAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinationAccount))
                .addGap(18, 18, 18)
                .addGroup(pnlMakeTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(18, 18, 18)
                .addComponent(btnMakeTransaction)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pnlMain.addTab("Make Transaction", pnlMakeTransaction);

        lblListUsers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblListUsers.setText("List Users");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Age", "Number of Accounts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrlUserList.setViewportView(tblUsers);

        btnRefreshUserList.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRefreshUserList.setText("Refresh");
        btnRefreshUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshUserListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserListLayout = new javax.swing.GroupLayout(pnlUserList);
        pnlUserList.setLayout(pnlUserListLayout);
        pnlUserListLayout.setHorizontalGroup(
            pnlUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserListLayout.createSequentialGroup()
                        .addComponent(scrlUserList, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlUserListLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblListUsers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshUserList)
                        .addGap(88, 88, 88))))
        );
        pnlUserListLayout.setVerticalGroup(
            pnlUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListUsers)
                    .addComponent(btnRefreshUserList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlUserList, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMain.addTab("List Users", pnlUserList);

        lblListAccounts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblListAccounts.setText("List Accounts");

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "User ID", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrlAccountList.setViewportView(tblAccounts);

        btnRefreshAccountList.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRefreshAccountList.setText("Refresh");
        btnRefreshAccountList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAccountListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountListLayout = new javax.swing.GroupLayout(pnlAccountList);
        pnlAccountList.setLayout(pnlAccountListLayout);
        pnlAccountListLayout.setHorizontalGroup(
            pnlAccountListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlAccountList, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlAccountListLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblListAccounts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshAccountList)
                .addGap(90, 90, 90))
        );
        pnlAccountListLayout.setVerticalGroup(
            pnlAccountListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlAccountListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListAccounts)
                    .addComponent(btnRefreshAccountList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlAccountList, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMain.addTab("List Accounts", pnlAccountList);

        lblListTransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblListTransactions.setText("List Transactions");

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Source Account ID", "Destination Account ID", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlTransactionList.setViewportView(tblTransactions);

        btnRefreshTransactionList.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRefreshTransactionList.setText("Refresh");
        btnRefreshTransactionList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTransactionListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTransactionListLayout = new javax.swing.GroupLayout(pnlTransactionList);
        pnlTransactionList.setLayout(pnlTransactionListLayout);
        pnlTransactionListLayout.setHorizontalGroup(
            pnlTransactionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlTransactionList, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTransactionListLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblListTransactions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshTransactionList)
                .addGap(89, 89, 89))
        );
        pnlTransactionListLayout.setVerticalGroup(
            pnlTransactionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlTransactionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListTransactions)
                    .addComponent(btnRefreshTransactionList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlTransactionList, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMain.addTab("List Transactions", pnlTransactionList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        int id = Integer.parseInt(txtID.getText());
        String firstname = txtFirstName.getText();
        String lastname = txtLastName.getText();
        int age = Integer.parseInt(txtAge.getText());
        
        Response response = UserController.createUser(id, firstname, lastname, String.valueOf(age));
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            
            txtID.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtAge.setText("");
        }

    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        int userId = Integer.parseInt(txtUserID.getText());
        double initialBalance = Double.parseDouble(txtInitialBalance.getText());
        
        Response response = AccountController.createAccount(String.valueOf(userId), String.valueOf(initialBalance));

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            txtUserID.setText("");
            txtInitialBalance.setText("");
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnMakeTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeTransactionActionPerformed
        try {
            
            String type = cmbTransactionType.getItemAt(cmbTransactionType.getSelectedIndex());
            String sourceAccountId = txtSourceAccount.getText();
            String destinationAccountId = txtDestinationAccount.getText();
            String amountStr = txtAmount.getText();

            
            Response response = TransactionController.createTransaction(type, sourceAccountId, destinationAccountId, amountStr);

            
            if (response.getStatus() >= 500) {
                JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
            } else if (response.getStatus() >= 400) {
                JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, response.getMessage(), "Transaction Successful", JOptionPane.INFORMATION_MESSAGE);
            }

            
            txtSourceAccount.setText("");
            txtDestinationAccount.setText("");
            txtAmount.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMakeTransactionActionPerformed

    private void btnRefreshUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshUserListActionPerformed

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);

        
        Response response = UserController.getAllUsers();

       if(response.getStatus()>=500){
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            @SuppressWarnings("unchecked")
            List<User> users = (List<User>) response.getData();
            
            users.sort((user1, user2) -> Integer.compare(user1.getId(), user2.getId()));

            for (User user : users) {
                model.addRow(new Object[]{user.getId(), user.getFirstname() + " " + user.getLastname(), user.getAge(), user.getNumAccounts()});
            }    
        }
    }//GEN-LAST:event_btnRefreshUserListActionPerformed

    private void btnRefreshAccountListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAccountListActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblAccounts.getModel();
        model.setRowCount(0);
        
        Response response = AccountController.getAllAccounts();
        
        if(response.getStatus()>=500){
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            @SuppressWarnings("unchecked")
            List<Account> accounts = (List<Account>) response.getData();
            
            accounts.sort((account1, account2) -> account1.getId().compareTo(account2.getId()));

            for (Account account : accounts) {
                model.addRow(new Object[]{account.getId(), account.getOwnerId(), account.getBalance()});
            }
        }
    }//GEN-LAST:event_btnRefreshAccountListActionPerformed

    private void btnRefreshTransactionListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTransactionListActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblTransactions.getModel();
        model.setRowCount(0);
        
        Response response = TransactionController.getTransactions();
        
        if(response.getStatus()>=500){
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            @SuppressWarnings("unchecked")
            List<Transaction> transactions = (List<Transaction>) response.getData();
            

            for (Transaction transaction : transactions) {
                model.addRow(new Object[]{transaction.getTypeString(), transaction.getAccount(), transaction.getDestinationAccount(), transaction.getAmount()});
            }
        }
    }//GEN-LAST:event_btnRefreshTransactionListActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnMakeTransaction;
    private javax.swing.JButton btnRefreshAccountList;
    private javax.swing.JButton btnRefreshTransactionList;
    private javax.swing.JButton btnRefreshUserList;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JComboBox<String> cmbTransactionType;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblDestinationAccount;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInitialBalance;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblListAccounts;
    private javax.swing.JLabel lblListTransactions;
    private javax.swing.JLabel lblListUsers;
    private javax.swing.JLabel lblMakeTransaction;
    private javax.swing.JLabel lblRegisterUser;
    private javax.swing.JLabel lblSourceAccount;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel pnlAccountList;
    private javax.swing.JPanel pnlCreateAccount;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JPanel pnlMakeTransaction;
    private javax.swing.JPanel pnlRegisterUser;
    private javax.swing.JPanel pnlTransactionList;
    private javax.swing.JPanel pnlUserList;
    private javax.swing.JScrollPane scrlAccountList;
    private javax.swing.JScrollPane scrlTransactionList;
    private javax.swing.JScrollPane scrlUserList;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDestinationAccount;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInitialBalance;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSourceAccount;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
